//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lensert {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt, Shift, R")]
        public global::Shortcut.Hotkey HotkeySelectRegion {
            get {
                return ((global::Shortcut.Hotkey)(this["HotkeySelectRegion"]));
            }
            set {
                this["HotkeySelectRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt, Shift, F")]
        public global::Shortcut.Hotkey HotkeySelectFullscreen {
            get {
                return ((global::Shortcut.Hotkey)(this["HotkeySelectFullscreen"]));
            }
            set {
                this["HotkeySelectFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt, Shift, W")]
        public global::Shortcut.Hotkey HotkeySelectWindow {
            get {
                return ((global::Shortcut.Hotkey)(this["HotkeySelectWindow"]));
            }
            set {
                this["HotkeySelectWindow"] = value;
            }
        }
    }
}
